"""123

Revision ID: 524237071e55
Revises: 7f295a746831
Create Date: 2025-10-23 16:39:09.446834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524237071e55'
down_revision = '7f295a746831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

