"""описание изменений

Revision ID: 7f295a746831
Revises: 001
Create Date: 2025-10-23 08:28:12.784302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f295a746831'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # Простая миграция: поменять типы колонок с VARCHAR -> INTEGER.
    # Мы не выполняем предварительную чистку данных здесь — предполагаем
    # что база будет пересоздана (или в ней нет нечисловых значений).
    op.alter_column(
        'orders', 'quantity',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="quantity::integer",
    )

    op.alter_column(
        'vegetables', 'weight',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="weight::integer",
    )

    op.alter_column(
        'vegetables', 'price',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="price::integer",
    )

    op.alter_column(
        'vegetables', 'length',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="length::integer",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vegetables', 'length',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('vegetables', 'price',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('vegetables', 'weight',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('orders', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###

